name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:
  pr_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup project
        uses: ./.github/actions/setup-project



        